apiVersion: v1
kind: Service
metadata:
  name: service-product
spec:
  selector:
    app: service-product
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product
spec:
  selector:
    matchLabels:
      app: service-product
  replicas: 1
  template:
    metadata:
      labels:
        app: service-product
    spec:
      containers:
        - name: server
          image: eliseevas/service-product
          ports:
            - name: http
              containerPort: 8081

---